name: click
description: A new Flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+14

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  font_awesome_flutter: ^10.2.1
  carousel_slider: ^4.1.1
  banner_carousel: ^1.2.1
  clipboard: ^0.1.3
  fluttertoast: ^8.0.9
  youtube_player_flutter: ^8.1.0
  http: ^0.13.5
  flutter_secure_storage: ^6.1.0
  screenshot: ^2.1.0
  path_provider: ^2.0.11
  share_plus: ^7.0.2
  pdf: ^3.8.4
  shared_preferences: ^2.0.15
  permission_handler: ^10.2.0
  firebase_core: ^2.3.0
  url_launcher: ^6.1.7
  flutter_colorpicker: ^1.0.3
  firebase_auth: ^4.2.0
  google_sign_in: ^5.4.2
  flutter_login_facebook: ^1.7.0
  flutter_facebook_auth: ^5.0.6
  flutter_launcher_icons: ^0.11.0
  razorpay_flutter: ^1.3.4
  flutter_svg: ^1.1.6
  flutter_widget_from_html: ^0.9.1
  otp_text_field: ^1.1.3
  intl: ^0.17.0
  dotted_border: ^2.0.0+3
  firebase_dynamic_links: ^5.1.1
  video_player: ^2.6.1
  flutter_ffmpeg: ^0.4.2
  file_picker: ^5.2.10
  cached_network_image: ^3.2.3
  percent_indicator: ^4.2.3
  firebase_messaging: ^14.6.1
  curved_navigation_bar: ^1.0.3
  connectivity_plus: ^4.0.1
  vector_math: ^2.1.4
  # device_info_plus: ^9.0.2
  flutter_windowmanager: ^0.2.0
  image_cropper: ^4.0.1
  sms_autofill: ^2.3.0

flutter_icons:
  image_path: "assets/instapost.png"
  android: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/festivalframe/
    - assets/festivalprofile/
    - assets/cscprofile/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
    - family: EkMukta-Regular
      fonts:
        - asset: assets/fonts/EkMukta-Regular.ttf
    - family: EkMukta-Medium
      fonts:
        - asset: assets/fonts/ek-mukta.medium.ttf
    - family: EkMukta-Bold
      fonts:
        - asset: assets/fonts/EkMukta-Bold.ttf
    - family: LaBelleAurore
      fonts:
        - asset: assets/fonts/LaBelleAurore-Regular.ttf
    - family: SHREE-DEV7-4909
      fonts:
        - asset: assets/fonts/0.ttf
    - family: SHREE-DEV7-1089
      fonts:
        - asset: assets/fonts/1.ttf
    - family: SHREE-DEV7-2317
      fonts:
        - asset: assets/fonts/2.ttf
    - family: SHREE-DEV7-3687
      fonts:
        - asset: assets/fonts/3.ttf
    - family: SHREE-DEV7-2336
      fonts:
        - asset: assets/fonts/4.ttf
    - family: SHREE-DEV7-3690
      fonts:
        - asset: assets/fonts/5.ttf
    - family: balbharati
      fonts:
        - asset: assets/fonts/BalBharatiDev02.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Anek-Light
      fonts:
        - asset: assets/fonts/AnekDevanagari-Light.ttf
    - family: Anek-Regular
      fonts:
        - asset: assets/fonts/AnekDevanagari-Regular.ttf
    - family: Anek-SemiBold
      fonts:
        - asset: assets/fonts/AnekDevanagari-SemiBold.ttf
    - family: Gotu-Regular
      fonts:
        - asset: assets/fonts/Gotu-Regular.ttf
    - family: Hind-Bold
      fonts:
        - asset: assets/fonts/Hind-Bold.ttf
    - family: Hind-Regular
      fonts:
        - asset: assets/fonts/Hind-Regular.ttf
    - family: Khand-Bold
      fonts:
        - asset: assets/fonts/Khand-Bold.ttf
    - family: Khand-Regular
      fonts:
        - asset: assets/fonts/Khand-Regular.ttf
    - family: Khand-SemiBold
      fonts:
        - asset: assets/fonts/Khand-SemiBold.ttf
    - family: NotoSerif-Regular
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
    - family: NotoSerif-SemiBold
      fonts:
        - asset: assets/fonts/NotoSerif-SemiBold.ttf
    - family: TiroDevanagariMarathi-Regular
      fonts:
        - asset: assets/fonts/TiroDevanagariMarathi-Regular.ttf
    - family: news706
      fonts:
        - asset: assets/fonts/news 706 bold bt.ttf
    - family: Mukta-Semibold
      fonts:
        - asset: assets/fonts/Mukta-SemiBold.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  # module:
  #   androidX: true
  #   androidPackage: com.example.click
  #   iosBundleIdentifier: com.example.click
